### ISSUE TITLE
Research existing Java solutions that produce GraphQL schema

### ISSUE THREAD

**Issue by wtrocki** [graphqlcrud/graphqlcrud-java#2]

**Comment by ani-sha** [comment]
@wtrocki starting with rdbms-to-graphql.

**Comment by ani-sha** [comment]
@rareddy and I discussed the rdbms-graphql library, it has some issues while running. It does not provide any error msg to further debug it. So instead of converting it to the maven project and then using it, I suggest we can take some code and write a basic model for this quarkus application instead of using the library.

**Comment by rareddy** [comment]
Yeah, there is not much in this library, suggest take whatever is needed and start building on top of it for graphqlcrud

**Comment by wtrocki** [comment]
+100

**Comment by ani-sha** [comment]
Good to close? @wtrocki

**Comment by wtrocki** [comment]
Yes! Amazing Work!
